packages:
  - name: docker
    type: docker
    srcs:
      - "startup.sh"
      - "supervisor-ide-config.json"
      - "index.html"
    argdeps:
      - imageRepoBase
    config:
      dockerfile: leeway.Dockerfile
      metadata:
        helm-component: workspace.ideaImage
      image:
        - ${imageRepoBase}/ide/idea-code-with-me:${version}
        - ${imageRepoBase}/ide/idea-code-with-me:commit-${__git_commit}
